version: '3.6'

volumes:
  websocket_config:
  core_db:
  core_cache:
  redis_data:
  core_composer_cache:
  ws_composer_cache:
  website_composer_cache:
  website_nginx_logs:
  
services:
  platadmin:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    external_links:
      - core-db
    env_file:
      - .env
    secrets:
      - ftcbot-db-password
      - ftcbot-db-user
      - ftcbot-broker-password
      - ftcbot-broker-username
      - ftcbot-discord-auth-token
      - ftcbot-discord-token
      - ftcbot-website-session-key
    ports:
      - "9000"
    volumes:
      - .:/app/:z
    networks:
      ftcbot_dev:
      traefik:
    
  platadmin-front-server:
    image: nginx:1.15.1-alpine
    ports:
      - "7625:80"
    volumes:
      - .:/app:z
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - website_nginx_logs:/var/log/nginx
    labels:
      traefik.enable: true
      traefik.backend: discord_platadmin-front-server
      traefik.frontend.rule: Host:platform-admin.ftcbot-dev.test
      traefik.frontend.priority: 10
      traefik.docker.network: traefik
      traefik.port: 80
    networks:
      ftcbot_dev:
      traefik:
      
      
secrets:
  ftcbot-db-password:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-db-password
  ftcbot-db-user:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-db-user
  ftcbot-broker-password:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-broker-password
  ftcbot-broker-username:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-broker-username
  ftcbot-discord-auth-token:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-discord-auth-token
  ftcbot-discord-token:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-discord-token
  ftcbot-website-session-key:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-website-session-key 

      
networks:
  ftcbot_dev:
    external: true
  traefik:
    external: true
